
CREATE TABLE USUARIOS (
    ID INT PRIMARY KEY,
    NOME VARCHAR(45),
    EMAIL VARCHAR(45),
    TELEFONE INT,
    CPF INT,
    RG INT,
    TIPO ENUM('ADMIN', 'COMUM'),
    STATUS ENUM('ATIVO', 'INATIVO')
);

CREATE TABLE ENDERECOS (
    ID INT PRIMARY KEY,
    USUARIOS_ID INT,
    RUA VARCHAR(60),
    CIDADE VARCHAR(45),
    CEP VARCHAR(45),
    FOREIGN KEY (USUARIOS_ID) REFERENCES USUARIOS(ID)
);

CREATE TABLE ANUNCIOS (
    ID INT PRIMARY KEY,
    USUARIOS_ID INT,
    NOME_LIVRO VARCHAR(55),
    VALOR_ANUNCIO FLOAT,
    DESCRICAO VARCHAR(45),
    DATA_PUBLICACAO DATETIME,
    AVALIACAO VARCHAR(255),
    NOTA VARCHAR(45),
    STATUS ENUM('ATIVO', 'INATIVO', 'FINALIZADO'),
    FOREIGN KEY (USUARIOS_ID) REFERENCES USUARIOS(ID)
);

CREATE TABLE COMPRA (
    ID INT PRIMARY KEY,
    USUARIOS_ID INT,
    ANUNCIOS_ID INT,
    VALOR_PAGO FLOAT,
    DATA_PAGAMENTO DATETIME,
    CODIGOTRANSACAO VARCHAR(255),
    FOREIGN KEY (USUARIOS_ID) REFERENCES USUARIOS(ID),
    FOREIGN KEY (ANUNCIOS_ID) REFERENCES ANUNCIOS(ID)
);

CREATE TABLE TROCA (
    ID INT PRIMARY KEY,
    ANUNCIOS_ID_1 INT,
    ANUNCIOS_ID_2 INT,
    DATA_TROCA DATETIME,
    FOREIGN KEY (ANUNCIOS_ID_1) REFERENCES ANUNCIOS(ID),
    FOREIGN KEY (ANUNCIOS_ID_2) REFERENCES ANUNCIOS(ID)
);

CREATE TABLE DENUNCIA (
    ID INT PRIMARY KEY,
    DESCRICAO VARCHAR(255),
    ANUNCIOS_ID INT,
    USUARIOS_ID INT,
    FOREIGN KEY (ANUNCIOS_ID) REFERENCES ANUNCIOS(ID),
    FOREIGN KEY (USUARIOS_ID) REFERENCES USUARIOS(ID)
);